spring:
  profiles:
    active: dev


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/dbo
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: dev-user
      password: dev-password

welcome:
  message: "Student Service is Up and Running"

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans
---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/dbo
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: qa-user
      password: qa-password
welcome:
  message: "Student Service is Up and Running for QA"
